name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Project Files
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing all files:"
          ls -la

      - name: Install Dependencies
        run: npm install
        working-directory: .  # Change this if package.json is inside a subfolder (e.g., 'next-app')

      - name: Build Next.js App
        run: npm run build
        working-directory: .  # Update this if needed

      - name: Run Next.js App (Optional for Testing)
        run: npm start &
       
deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
        - name: Checkout Code
        uses: actions/checkout@v3

        - name: Deploy to Server
        run: |
            echo "Deploying application..."
            # Add your deployment commands here (e.g., SSH into server, upload files)
